[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
AstroFITS = "34e54ef0-c5bf-48ab-9e5d-cca51f35ed77"
FITSHeaders = "8163a04c-c153-4fb1-a498-3402381ec208"

[compat]
Documenter = "1"
julia = "1"
